import CustomDump
import GraphQL
import XCTest

@testable import GraphQLSchemaCodeGen

final class GeneratorTests: XCTestCase {
    func testComment() throws {
        let generator = try Generator()
        generator.comment("Helpful comment")

        let expected =
            """
            // Helpful comment

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testHeader() throws {
        let generator = try Generator()
        generator.printHeader()

        let expected =
            """
            //
            // DO NOT EDIT.
            // swift-format-ignore-file
            //
            // Generated by GraphQLSchemaCodeGen
            //

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testImportsDefault() throws {
        let generator = try Generator()
        generator.printImports()

        let expected =
            """

            import Foundation
            import GraphQL
            import Graphiti

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testImportsCustomImports() throws {
        let generator = try Generator(
            options: GeneratorOptions(additionalImports: ["Pioneer", "Vapor"]))
        generator.printImports()

        let expected =
            """

            import Foundation
            import GraphQL
            import Graphiti
            import Pioneer
            import Vapor

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testNamespaceDefault() throws {
        let generator = try Generator()
        generator.printNamespace()

        let expected =
            """

            enum GeneratedSchema {}

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testNamespaceCustomNamespace() throws {
        let generator = try Generator(options: GeneratorOptions(namespace: "Chat"))
        generator.printNamespace()

        let expected =
            """

            enum ChatSchema {}

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testSDLDefault() throws {
        let generator = try Generator()
        generator.printSDL()

        let expected =
            """

            // MARK: - SDL
            extension GeneratedSchema {
              static let sdl: String =
              \"\"\"
              \"\"\"
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testSDLCustomSchemas() throws {
        let schema1 = """
            type Schema1 {}

            """
        let schema2 = """
            type Schema2 {}

            """
        let generator = try Generator(schemas: [schema1, schema2])
        generator.printSDL()

        let expected =
            """

            // MARK: - SDL
            extension GeneratedSchema {
              static let sdl: String =
              \"\"\"
              type Schema1 {}

              type Schema2 {}
              \"\"\"
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testTypeMappingDefault() throws {
        let generator = try Generator()
        generator.printTypeMapping()

        let expected =
            """
            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testTypeMappingCustomMappings() throws {
        let generator = try Generator(
            options: GeneratorOptions(typeMapping: [
                "DateTime": "Foundation.Date", "LocalTime": "Foundation.String",
            ]))
        generator.printTypeMapping()

        let expected =
            """

            // MARK: - Type Mapping
            extension GeneratedSchema {
              typealias DateTime = Foundation.Date
              typealias LocalTime = Foundation.String
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testObjectTypes() throws {
        let schema =
            """
            type Message {
                id: ID!
                body: String!
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        let expected =
            """

            // MARK: - Types
            extension GeneratedSchema {
              struct Message: Codable, Sendable {
                let id: ID
                let body: String
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testObjectTypesComputedField() throws {
        let schema =
            """
            type Message {
                id: ID!
                body: String!
                viewedBy(userId: ID!): Bool
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        let expected =
            """

            // MARK: - Types
            extension GeneratedSchema {
              struct Message: Codable, Sendable {
                let id: ID
                let body: String

                struct ViewedByArguments: Codable, Sendable {
                  let userId: ID
                }

                func _viewedBy<ContextType>(context: ContextType, args: ViewedByArguments) async throws -> Bool? {
                  guard let resolver = self as? any GeneratedSchema.Message.Resolver<ContextType> else {
                    throw GeneratedSchemaError(description: "Message.viewedBy is unimplemented")
                  }

                  return try await resolver.viewedBy(context: context, args: args)
                }

                protocol Resolver<ContextType> {
                  associatedtype ContextType

                  func viewedBy(context: ContextType, args: ViewedByArguments) async throws -> Bool?
                }
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testObjectTypeWithCustomComputedFields() throws {
        let schema =
            """
            type Planet {
                id: ID!
                galaxy: Galaxy
            }
            """
        let generator = try Generator(
            options: GeneratorOptions(computedFields: [
                "Planet": ["galaxy"]
            ]),
            schemas: [schema]
        )
        try generator.printObjectTypes()

        let expected =
            """

            // MARK: - Types
            extension GeneratedSchema {
              struct Planet: Codable, Sendable {
                let id: ID

                func _galaxy<ContextType>(context: ContextType, args: NoArguments) async throws -> Galaxy? {
                  guard let resolver = self as? any GeneratedSchema.Planet.Resolver<ContextType> else {
                    throw GeneratedSchemaError(description: "Planet.galaxy is unimplemented")
                  }

                  return try await resolver.galaxy(context: context, args: args)
                }

                protocol Resolver<ContextType> {
                  associatedtype ContextType

                  func galaxy(context: ContextType, args: NoArguments) async throws -> Galaxy?
                }
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testObjectTypesMultipleComputedFields() throws {
        let schema =
            """
            type Message {
                id: ID!
                body: String!
                viewedBy(userId: ID!): Bool
                likedBy(userId: ID!): Bool
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        let expected =
            """

            // MARK: - Types
            extension GeneratedSchema {
              struct Message: Codable, Sendable {
                let id: ID
                let body: String

                struct ViewedByArguments: Codable, Sendable {
                  let userId: ID
                }

                func _viewedBy<ContextType>(context: ContextType, args: ViewedByArguments) async throws -> Bool? {
                  guard let resolver = self as? any GeneratedSchema.Message.Resolver<ContextType> else {
                    throw GeneratedSchemaError(description: "Message.viewedBy is unimplemented")
                  }

                  return try await resolver.viewedBy(context: context, args: args)
                }

                struct LikedByArguments: Codable, Sendable {
                  let userId: ID
                }

                func _likedBy<ContextType>(context: ContextType, args: LikedByArguments) async throws -> Bool? {
                  guard let resolver = self as? any GeneratedSchema.Message.Resolver<ContextType> else {
                    throw GeneratedSchemaError(description: "Message.likedBy is unimplemented")
                  }

                  return try await resolver.likedBy(context: context, args: args)
                }

                protocol Resolver<ContextType> {
                  associatedtype ContextType

                  func viewedBy(context: ContextType, args: ViewedByArguments) async throws -> Bool?
                  func likedBy(context: ContextType, args: LikedByArguments) async throws -> Bool?
                }
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testObjectTypesWithFederationKey() throws {
        let schema =
            """
            type Message @key(fields: "id") {
                id: ID!
                body: String!
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        let expected =
            """

            // MARK: - Types
            extension GeneratedSchema {
              struct Message: Codable, Sendable {
                let id: ID
                let body: String

                struct Key: Codable, Sendable {
                  let id: ID
                }
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testObjectTypesWithMultipleFederationKey() throws {
        let schema =
            """
            type Message @key(fields: "id") @key(fields: "hash") {
                id: ID!
                hash: String!
                body: String!
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        let expected =
            """

            // MARK: - Types
            extension GeneratedSchema {
              struct Message: Codable, Sendable {
                let id: ID
                let hash: String
                let body: String

                struct Key0: Codable, Sendable {
                  let id: ID
                }

                struct Key1: Codable, Sendable {
                  let hash: String
                }
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testObjectTypesWithComputedFieldsAndFederationKeys() throws {
        let schema =
            """
            type Message @key(fields: "id") {
                id: ID!
                body: String!
                viewedBy(userId: ID!): Bool
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        let expected =
            """

            // MARK: - Types
            extension GeneratedSchema {
              struct Message: Codable, Sendable {
                let id: ID
                let body: String

                struct ViewedByArguments: Codable, Sendable {
                  let userId: ID
                }

                func _viewedBy<ContextType>(context: ContextType, args: ViewedByArguments) async throws -> Bool? {
                  guard let resolver = self as? any GeneratedSchema.Message.Resolver<ContextType> else {
                    throw GeneratedSchemaError(description: "Message.viewedBy is unimplemented")
                  }

                  return try await resolver.viewedBy(context: context, args: args)
                }

                protocol Resolver<ContextType> {
                  associatedtype ContextType

                  func viewedBy(context: ContextType, args: ViewedByArguments) async throws -> Bool?
                }

                struct Key: Codable, Sendable {
                  let id: ID
                }
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testObjectTypesWithNestedFederationKey() throws {
        let schema =
            """
            type User {
                id: ID!
                username: String!
            }

            type Conversation @key(fields: "creator { id } guest { id }") {
                creator: User!
                guest: User!
                title: String
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        let expected =
            """

            // MARK: - Types
            extension GeneratedSchema {
              struct User: Codable, Sendable {
                let id: ID
                let username: String
              }

              struct Conversation: Codable, Sendable {
                let creator: User
                let guest: User
                let title: String?

                struct Key: Codable, Sendable {
                  struct Creator: Codable, Sendable {
                    let id: ID
                  }
                  struct Guest: Codable, Sendable {
                    let id: ID
                  }
                  let creator: Creator
                  let guest: Guest
                }
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testObjectTypesWithMixedFlatAndNestedKeys() throws {
        let schema =
            """
            type User @key(fields: "id") {
                id: ID!
                username: String!
            }

            type Conversation @key(fields: "creator { id } guest { id }") {
                creator: User!
                guest: User!
                title: String
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        let expected =
            """

            // MARK: - Types
            extension GeneratedSchema {
              struct User: Codable, Sendable {
                let id: ID
                let username: String

                struct Key: Codable, Sendable {
                  let id: ID
                }
              }

              struct Conversation: Codable, Sendable {
                let creator: User
                let guest: User
                let title: String?

                struct Key: Codable, Sendable {
                  struct Creator: Codable, Sendable {
                    let id: ID
                  }
                  struct Guest: Codable, Sendable {
                    let id: ID
                  }
                  let creator: Creator
                  let guest: Guest
                }
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testResolverProtocolWithNestedFederationKey() throws {
        let schema =
            """
            type User {
                id: ID!
                username: String!
            }

            type Conversation @key(fields: "creator { id } guest { id }") {
                creator: User!
                guest: User!
                title: String
            }

            type Query {
                conversation(id: ID!): Conversation
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printResolverProtocol()

        let expected =
            """

            // MARK: - Resolver Protocol
            extension GeneratedSchema {
              protocol GeneratedResolver: Sendable {
                associatedtype ContextType

                func conversation(context: ContextType, args: ConversationArguments) async throws -> Conversation?
                func conversation(context: ContextType, key: Conversation.Key) async throws -> Conversation?
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testSchemaBuilderWithNestedFederationKey() throws {
        let schema =
            """
            type User {
                id: ID!
                username: String!
            }

            type Conversation @key(fields: "creator { id } guest { id }") {
                creator: User!
                guest: User!
                title: String
            }

            type Query {
                conversation(id: ID!): Conversation
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printSchemaBuilder()

        let expected =
            """

            // MARK: - Schema Builder
            extension GeneratedSchema {
              static func schema<Resolver>(coders: Coders = Coders()) throws -> Schema<Resolver, Resolver.ContextType> where Resolver: GeneratedResolver {
                try SchemaBuilder(Resolver.self, Resolver.ContextType.self)
                  .setCoders(to: coders)
                  .setFederatedSDL(to: sdl)
                  .add {
                    Type(User.self, as: "User") {
                      Field("id", at: \\.id)
                      Field("username", at: \\.username)
                    }
                    Type(Conversation.self, as: "Conversation") {
                      Field("creator", at: \\.creator)
                      Field("guest", at: \\.guest)
                      Field("title", at: \\.title)
                    }
                    .key(at: Resolver.conversation) {
                      Argument("creator", at: \\.creator)
                      Argument("guest", at: \\.guest)
                    }
                  }
                  .addQuery {
                    Field("conversation", at: Resolver.conversation) {
                      Argument("id", at: \\.id)
                    }
                  }
                  .build()
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testObjectTypesWithInterfaces() throws {
        let schema =
            """
            interface Node {
              id: ID!
            }

            type Starship implements Node {
              id: ID!
              name: String!
            }
            """

        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        let expected =
            """

            // MARK: - Types
            extension GeneratedSchema {
              struct Starship: Node, Codable, Sendable {
                let id: ID
                let name: String
              }

              protocol Node: Sendable {
                var id: ID { get }
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testObjectResolverDefaultImplementation() throws {
        let schema =
            """
            type Message {
                id: ID!
                body: String!
                viewedBy(userId: ID!): Boolean
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectResolverDefaultImplementation()

        let expected =
            """

            extension GeneratedSchema.Message.Resolver {
              func viewedBy(context: ContextType, args: GeneratedSchema.Message.ViewedByArguments) async throws -> Bool? {
                throw GeneratedSchemaError(description: "Message.viewedBy is unimplemented.")
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testInputObjectAndEnum() throws {
        let schema =
            """
            type Message {
                id: ID!
                body: String!
            }

            input SendMessageInput {
                body: String!
            }

            enum MessageType {
              URGENT
              NORMAL
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        let expected =
            """

            // MARK: - Types
            extension GeneratedSchema {
              struct Message: Codable, Sendable {
                let id: ID
                let body: String
              }

              struct SendMessageInput: Codable, Sendable {
                let body: String
              }

              enum MessageType: String, Codable, Sendable {
                case urgent = "URGENT"
                case normal = "NORMAL"
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testResolverArguments() throws {
        let schema =
            """
            type Query {
                history(room: String!): [Message!]!
            }

            type Mutation {
                sendMessage(room: String!, message: String!): Message!
            }

            type Subscription {
                messages(room: String!): Message!
            }
            """

        let generator = try Generator(schemas: [schema])
        try generator.printResolverArguments()

        let expected =
            """

            // MARK: - Resolver Arguments
            extension GeneratedSchema {
              struct HistoryArguments: Codable, Sendable {
                let room: String
              }

              struct SendMessageArguments: Codable, Sendable {
                let room: String
                let message: String
              }

              struct MessagesArguments: Codable, Sendable {
                let room: String
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testResolverProtocol() throws {
        let schema =
            """
            type Query {
                history(room: String!): [Message!]!
            }

            type Mutation {
                sendMessage(room: String!, message: String!): Message!
            }

            type Subscription {
                messages(room: String!): Message!
            }
            """

        let generator = try Generator(schemas: [schema])
        try generator.printResolverProtocol()

        let expected =
            """

            // MARK: - Resolver Protocol
            extension GeneratedSchema {
              protocol GeneratedResolver: Sendable {
                associatedtype ContextType

                func history(context: ContextType, args: HistoryArguments) async throws -> [Message]
                func sendMessage(context: ContextType, args: SendMessageArguments) async throws -> Message
                func messages(context: ContextType, args: MessagesArguments) async throws -> EventStream<Message>
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testResolverProtocolWithFederationKeys() throws {
        let schema =
            """
            type Message @key(fields: "id") {
                id: ID!
                body: String!
            }

            type Query {
                history(room: String!): [Message!]!
            }

            type Mutation {
                sendMessage(room: String!, message: String!): Message!
            }

            type Subscription {
                messages(room: String!): Message!
            }
            """

        let generator = try Generator(schemas: [schema])
        try generator.printResolverProtocol()

        let expected =
            """

            // MARK: - Resolver Protocol
            extension GeneratedSchema {
              protocol GeneratedResolver: Sendable {
                associatedtype ContextType

                func history(context: ContextType, args: HistoryArguments) async throws -> [Message]
                func sendMessage(context: ContextType, args: SendMessageArguments) async throws -> Message
                func messages(context: ContextType, args: MessagesArguments) async throws -> EventStream<Message>
                func message(context: ContextType, key: Message.Key) async throws -> Message?
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testResolverProtocolWithFederationMultipleKeys() throws {
        let schema =
            """
            type Message @key(fields: "id") @key(fields: "hash") {
                id: ID!
                hash: String!
                body: String!
            }

            type User @key(fields: "id") {
                id: ID!
            }

            type Query {
                history(room: String!): [Message!]!
            }

            type Mutation {
                sendMessage(room: String!, message: String!): Message!
            }

            type Subscription {
                messages(room: String!): Message!
            }
            """

        let generator = try Generator(schemas: [schema])
        try generator.printResolverProtocol()

        let expected =
            """

            // MARK: - Resolver Protocol
            extension GeneratedSchema {
              protocol GeneratedResolver: Sendable {
                associatedtype ContextType

                func history(context: ContextType, args: HistoryArguments) async throws -> [Message]
                func sendMessage(context: ContextType, args: SendMessageArguments) async throws -> Message
                func messages(context: ContextType, args: MessagesArguments) async throws -> EventStream<Message>
                func message(context: ContextType, key: Message.Key0) async throws -> Message?
                func message(context: ContextType, key: Message.Key1) async throws -> Message?
                func user(context: ContextType, key: User.Key) async throws -> User?
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testResolverProtocolDefaultImplementationWithFederationKey() throws {
        let schema =
            """
            type Message @key(fields: "id") {
                id: ID!
                body: String!
            }

            type Query {
                history(room: String!): [Message!]!
            }

            type Mutation {
                sendMessage(room: String!, message: String!): Message!
            }

            type Subscription {
                messages(room: String!): Message!
            }
            """

        let generator = try Generator(schemas: [schema])
        try generator.printResolverProtocolDefaultImplemention()

        let expected =
            """

            // MARK: - Resolver Default Implemention
            extension GeneratedSchema.GeneratedResolver {
              func history(context: ContextType, args: GeneratedSchema.HistoryArguments) async throws -> [GeneratedSchema.Message] {
                throw GeneratedSchemaError(description: "Resolver for query.history is unimplemented.")
              }

              func sendMessage(context: ContextType, args: GeneratedSchema.SendMessageArguments) async throws -> GeneratedSchema.Message {
                throw GeneratedSchemaError(description: "Resolver for mutation.sendMessage is unimplemented.")
              }

              func messages(context: ContextType, args: GeneratedSchema.MessagesArguments) async throws -> EventStream<GeneratedSchema.Message> {
                throw GeneratedSchemaError(description: "Resolver for subscription.messages is unimplemented.")
              }

              func message(context: ContextType, key: GeneratedSchema.Message.Key) async throws -> GeneratedSchema.Message? {
                throw GeneratedSchemaError(description: "Resolver for federation.Message.Key is unimplemented.")
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testSchemaBuilder() throws {
        let schema =
            """
            scalar ID

            type Message @key(fields: "id") {
                id: ID!
                body: String!
                viewedBy(userId: ID!): Bool
            }

            input SendMessageInput {
                room: String!
                message: String!
            }

            enum MessageType {
                URGENT
                NORMAL
            }

            type Query {
                history(room: String!): [Message!]!
            }

            type Mutation {
                sendMessage(room: String!, message: String!): Message!
            }

            type Subscription {
                messages(room: String!): Message!
            }
            """

        let generator = try Generator(schemas: [schema])
        try generator.printSchemaBuilder()

        let expected =
            """

            // MARK: - Schema Builder
            extension GeneratedSchema {
              static func schema<Resolver>(coders: Coders = Coders()) throws -> Schema<Resolver, Resolver.ContextType> where Resolver: GeneratedResolver {
                try SchemaBuilder(Resolver.self, Resolver.ContextType.self)
                  .setCoders(to: coders)
                  .setFederatedSDL(to: sdl)
                  .add {
                    Scalar(ID.self, as: "ID")
                    Type(Message.self, as: "Message") {
                      Field("id", at: \\.id)
                      Field("body", at: \\.body)
                      Field("viewedBy", at: Message._viewedBy) {
                        Argument("userId", at: \\.userId)
                      }
                    }
                    .key(at: Resolver.message) {
                      Argument("id", at: \\.id)
                    }
                    Input(SendMessageInput.self, as: "SendMessageInput") {
                      InputField("room", at: \\.room)
                      InputField("message", at: \\.message)
                    }
                    Enum(MessageType.self) {
                      Value(.urgent)
                      Value(.normal)
                    }
                  }
                  .addQuery {
                    Field("history", at: Resolver.history) {
                      Argument("room", at: \\.room)
                    }
                  }
                  .addMutation {
                    Field("sendMessage", at: Resolver.sendMessage) {
                      Argument("room", at: \\.room)
                      Argument("message", at: \\.message)
                    }
                  }
                  .addSubscription {
                    SubscriptionField("messages", as: Message.self, atSub: Resolver.messages) {
                      Argument("room", at: \\.room)
                    }
                  }
                  .build()
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testSchemaBuilderWithInterfaces() throws {
        let schema =
            """
            interface Node {
              id: ID!
            }

            type Starship implements Node {
              id: ID!
              name: String!
            }
            """

        let generator = try Generator(schemas: [schema])
        try generator.printSchemaBuilder()

        let expected =
            """

            // MARK: - Schema Builder
            extension GeneratedSchema {
              static func schema<Resolver>(coders: Coders = Coders()) throws -> Schema<Resolver, Resolver.ContextType> where Resolver: GeneratedResolver {
                try SchemaBuilder(Resolver.self, Resolver.ContextType.self)
                  .setCoders(to: coders)
                  .setFederatedSDL(to: sdl)
                  .add {
                    Type(Starship.self, as: "Starship", interfaces: [Node.self]) {
                      Field("id", at: \\.id)
                      Field("name", at: \\.name)
                    }
                    Interface(Node.self) {
                      Field("id", at: \\.id)
                    }
                  }
                  .build()
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testSchemaBuilderWithComputedFields() throws {
        let schema =
            """
            type Planet {
              id: ID!
              galaxy: Galaxy
            } 
            """

        let generator = try Generator(
            options: GeneratorOptions(computedFields: [
                "Planet": [
                    "galaxy"
                ]
            ]),
            schemas: [schema]
        )
        try generator.printSchemaBuilder()

        let expected =
            """

            // MARK: - Schema Builder
            extension GeneratedSchema {
              static func schema<Resolver>(coders: Coders = Coders()) throws -> Schema<Resolver, Resolver.ContextType> where Resolver: GeneratedResolver {
                try SchemaBuilder(Resolver.self, Resolver.ContextType.self)
                  .setCoders(to: coders)
                  .setFederatedSDL(to: sdl)
                  .add {
                    Type(Planet.self, as: "Planet") {
                      Field("id", at: \\.id)
                      Field("galaxy", at: Planet._galaxy)
                    }
                  }
                  .build()
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testGenerator() throws {
        let topicsSchema = try Bundle.module.contents(
            forResource: "Chat", withExtension: "graphqls")
        let federationSchema = try Bundle.module.contents(
            forResource: "Federation", withExtension: "graphqls")
        let expected = try Bundle.module.contents(
            forResource: "ChatSchema.swift", withExtension: "generated")

        let generator = try Generator(
            options: GeneratorOptions(
                namespace: "Chat",
                additionalImports: [
                    "Pioneer"
                ],
                typeMapping: [
                    "DateTime": "Foundation.Date"
                ]
            ),
            schemas: [
                topicsSchema,
                federationSchema,
            ]
        )

        try generator.generate()

        XCTAssertNoDifference(generator.code, expected)
    }

    // MARK: - Keyword Escaping Tests

    func testKeywordEscapingObjectFields() throws {
        let schema =
            """
            type Assignment {
                id: ID!
                operator: Person
                default: Boolean
                class: String
            }

            type Person {
                id: ID!
                name: String!
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        let expected =
            """

            // MARK: - Types
            extension GeneratedSchema {
              struct Assignment: Codable, Sendable {
                let id: ID
                let `operator`: Person?
                let `default`: Bool?
                let `class`: String?
              }

              struct Person: Codable, Sendable {
                let id: ID
                let name: String
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testKeywordEscapingInputFields() throws {
        let schema =
            """
            type Holder {
                id: ID!
            }

            input FilterInput {
                operator: String
                where: String
                in: [ID!]
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        let expected =
            """

            // MARK: - Types
            extension GeneratedSchema {
              struct Holder: Codable, Sendable {
                let id: ID
              }

              struct FilterInput: Codable, Sendable {
                let `operator`: String?
                let `where`: String?
                let `in`: [ID]
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testKeywordEscapingEnumCases() throws {
        let schema =
            """
            type Holder {
                id: ID!
            }

            enum BooleanResult {
                TRUE
                FALSE
                NIL
                DEFAULT
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        let expected =
            """

            // MARK: - Types
            extension GeneratedSchema {
              struct Holder: Codable, Sendable {
                let id: ID
              }

              enum BooleanResult: String, Codable, Sendable {
                case `true` = "TRUE"
                case `false` = "FALSE"
                case `nil` = "NIL"
                case `default` = "DEFAULT"
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testKeywordEscapingResolverProtocol() throws {
        let schema =
            """
            type Query {
                default(in: ID!): String
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printResolverArguments()

        let expected =
            """

            // MARK: - Resolver Arguments
            extension GeneratedSchema {
              struct DefaultArguments: Codable, Sendable {
                let `in`: ID
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testKeywordEscapingSchemaBuilder() throws {
        let schema =
            """
            type Assignment {
                id: ID!
                operator: String
                default: Boolean
            }

            input FilterInput {
                operator: String
                where: String
            }

            enum BooleanResult {
                TRUE
                FALSE
                DEFAULT
            }

            type Query {
                assignment(id: ID!): Assignment
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printSchemaBuilder()

        let expected =
            """

            // MARK: - Schema Builder
            extension GeneratedSchema {
              static func schema<Resolver>(coders: Coders = Coders()) throws -> Schema<Resolver, Resolver.ContextType> where Resolver: GeneratedResolver {
                try SchemaBuilder(Resolver.self, Resolver.ContextType.self)
                  .setCoders(to: coders)
                  .setFederatedSDL(to: sdl)
                  .add {
                    Type(Assignment.self, as: "Assignment") {
                      Field("id", at: \\.id)
                      Field("operator", at: \\.`operator`)
                      Field("default", at: \\.`default`)
                    }
                    Input(FilterInput.self, as: "FilterInput") {
                      InputField("operator", at: \\.`operator`)
                      InputField("where", at: \\.`where`)
                    }
                    Enum(BooleanResult.self) {
                      Value(.`true`)
                      Value(.`false`)
                      Value(.`default`)
                    }
                  }
                  .addQuery {
                    Field("assignment", at: Resolver.assignment) {
                      Argument("id", at: \\.id)
                    }
                  }
                  .build()
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testKeywordEscapingComputedField() throws {
        let schema =
            """
            type Task {
                id: ID!
                operator(role: String!): Person
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        let expected =
            """

            // MARK: - Types
            extension GeneratedSchema {
              struct Task: Codable, Sendable {
                let id: ID

                struct OperatorArguments: Codable, Sendable {
                  let role: String
                }

                func _operator<ContextType>(context: ContextType, args: OperatorArguments) async throws -> Person? {
                  guard let resolver = self as? any GeneratedSchema.Task.Resolver<ContextType> else {
                    throw GeneratedSchemaError(description: "Task.operator is unimplemented")
                  }

                  return try await resolver.`operator`(context: context, args: args)
                }

                protocol Resolver<ContextType> {
                  associatedtype ContextType

                  func `operator`(context: ContextType, args: OperatorArguments) async throws -> Person?
                }
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    // MARK: - Union Type Tests

    func testUnionTypes() throws {
        let schema =
            """
            type Dog {
                name: String!
                breed: String
            }

            type Cat {
                name: String!
                indoor: Boolean
            }

            union Pet = Dog | Cat

            type Owner {
                id: ID!
                pet: Pet
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        let expected =
            """

            // MARK: - Types
            extension GeneratedSchema {
              struct Dog: Pet, Codable, Sendable {
                let name: String
                let breed: String?
              }

              struct Cat: Pet, Codable, Sendable {
                let name: String
                let indoor: Bool?
              }

              struct Owner: Codable, Sendable {
                let id: ID

                func _pet<ContextType>(context: ContextType, args: NoArguments) async throws -> (any Pet)? {
                  guard let resolver = self as? any GeneratedSchema.Owner.Resolver<ContextType> else {
                    throw GeneratedSchemaError(description: "Owner.pet is unimplemented")
                  }

                  return try await resolver.pet(context: context, args: args)
                }

                protocol Resolver<ContextType> {
                  associatedtype ContextType

                  func pet(context: ContextType, args: NoArguments) async throws -> (any Pet)?
                }
              }

              protocol Pet: Sendable {
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testUnionSchemaBuilder() throws {
        let schema =
            """
            type Dog {
                name: String!
                breed: String
            }

            type Cat {
                name: String!
                indoor: Boolean
            }

            union Pet = Dog | Cat

            type Owner {
                id: ID!
                pet: Pet
            }

            type Query {
                owner(id: ID!): Owner
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printSchemaBuilder()

        let expected =
            """

            // MARK: - Schema Builder
            extension GeneratedSchema {
              static func schema<Resolver>(coders: Coders = Coders()) throws -> Schema<Resolver, Resolver.ContextType> where Resolver: GeneratedResolver {
                try SchemaBuilder(Resolver.self, Resolver.ContextType.self)
                  .setCoders(to: coders)
                  .setFederatedSDL(to: sdl)
                  .add {
                    Type(Dog.self, as: "Dog") {
                      Field("name", at: \\.name)
                      Field("breed", at: \\.breed)
                    }
                    Type(Cat.self, as: "Cat") {
                      Field("name", at: \\.name)
                      Field("indoor", at: \\.indoor)
                    }
                    Type(Owner.self, as: "Owner") {
                      Field("id", at: \\.id)
                      Field("pet", at: Owner._pet)
                    }
                    Union(Pet.self, members: Dog.self, Cat.self)
                  }
                  .addQuery {
                    Field("owner", at: Resolver.owner) {
                      Argument("id", at: \\.id)
                    }
                  }
                  .build()
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testUnionResolverDefaultImplementation() throws {
        let schema =
            """
            type Dog {
                name: String!
            }

            type Cat {
                name: String!
            }

            union Pet = Dog | Cat

            type Owner {
                id: ID!
                pet: Pet
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectResolverDefaultImplementation()

        let expected =
            """

            extension GeneratedSchema.Owner.Resolver {
              func pet(context: ContextType, args: NoArguments) async throws -> (any GeneratedSchema.Pet)? {
                throw GeneratedSchemaError(description: "Owner.pet is unimplemented.")
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    // MARK: - Interface-Typed Field Tests

    func testInterfaceTypedFieldAutoPromotion() throws {
        let schema =
            """
            interface Renderable {
                preview: String!
            }

            type RichText implements Renderable {
                preview: String!
                html: String!
            }

            type Card {
                id: ID!
                content: Renderable
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        let expected =
            """

            // MARK: - Types
            extension GeneratedSchema {
              struct RichText: Renderable, Codable, Sendable {
                let preview: String
                let html: String
              }

              struct Card: Codable, Sendable {
                let id: ID

                func _content<ContextType>(context: ContextType, args: NoArguments) async throws -> (any Renderable)? {
                  guard let resolver = self as? any GeneratedSchema.Card.Resolver<ContextType> else {
                    throw GeneratedSchemaError(description: "Card.content is unimplemented")
                  }

                  return try await resolver.content(context: context, args: args)
                }

                protocol Resolver<ContextType> {
                  associatedtype ContextType

                  func content(context: ContextType, args: NoArguments) async throws -> (any Renderable)?
                }
              }

              protocol Renderable: Sendable {
                var preview: String { get }
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testInterfaceTypedListFieldAutoPromotion() throws {
        let schema =
            """
            interface Renderable {
                preview: String!
            }

            type RichText implements Renderable {
                preview: String!
                html: String!
            }

            type Dashboard {
                id: ID!
                widgets: [Renderable!]!
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        let expected =
            """

            // MARK: - Types
            extension GeneratedSchema {
              struct RichText: Renderable, Codable, Sendable {
                let preview: String
                let html: String
              }

              struct Dashboard: Codable, Sendable {
                let id: ID

                func _widgets<ContextType>(context: ContextType, args: NoArguments) async throws -> [any Renderable] {
                  guard let resolver = self as? any GeneratedSchema.Dashboard.Resolver<ContextType> else {
                    throw GeneratedSchemaError(description: "Dashboard.widgets is unimplemented")
                  }

                  return try await resolver.widgets(context: context, args: args)
                }

                protocol Resolver<ContextType> {
                  associatedtype ContextType

                  func widgets(context: ContextType, args: NoArguments) async throws -> [any Renderable]
                }
              }

              protocol Renderable: Sendable {
                var preview: String { get }
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    // MARK: - Circular Type Detection Tests

    func testCircularTypeDetection() throws {
        let schema =
            """
            type Vehicle {
                id: ID!
                name: String!
                dispenser: Dispenser
            }

            type Dispenser {
                id: ID!
                status: String!
                vehicle: Vehicle
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        // At least one field in the cycle should be promoted to computed
        // The generated code should contain a Resolver protocol for the type that got the computed field
        let code = generator.code

        // Both types should be present as structs
        XCTAssert(code.contains("struct Vehicle: Codable, Sendable"), "Vehicle struct should be generated")
        XCTAssert(code.contains("struct Dispenser: Codable, Sendable"), "Dispenser struct should be generated")

        // At least one field should be computed (has a Resolver protocol)
        XCTAssert(
            code.contains("protocol Resolver<ContextType>"),
            "At least one type should have a Resolver protocol for cycle-breaking computed field"
        )

        // The computed field should use NoArguments (no GraphQL arguments)
        XCTAssert(
            code.contains("NoArguments"),
            "Cycle-breaking computed field should use NoArguments"
        )
    }

    func testSelfReferentialType() throws {
        let schema =
            """
            type Node {
                id: ID!
                children: [Node!]!
                parent: Node
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        let code = generator.code

        // children is an array, so it doesn't create a cycle (arrays store on heap)
        // parent is a direct reference, so it should be promoted to computed
        XCTAssert(code.contains("struct Node: Codable, Sendable"), "Node struct should be generated")
        XCTAssert(code.contains("let id: ID"), "id should be a stored property")
        XCTAssert(code.contains("let children: [Node]"), "children (array) should be stored")
        XCTAssert(
            code.contains("func _parent"),
            "parent should be promoted to computed field to break self-reference"
        )
    }

    func testCircularTypeSchemaBuilder() throws {
        let schema =
            """
            type Vehicle {
                id: ID!
                name: String!
                dispenser: Dispenser
            }

            type Dispenser {
                id: ID!
                status: String!
                vehicle: Vehicle
            }

            type Query {
                vehicle(id: ID!): Vehicle
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printSchemaBuilder()

        let code = generator.code

        // The cycle-breaking field should use function reference (Type._field) not keypath
        let hasFunctionRef =
            code.contains("Vehicle._dispenser") || code.contains("Dispenser._vehicle")
        XCTAssert(
            hasFunctionRef,
            "Cycle-breaking field should use function reference in schema builder"
        )
    }

    // MARK: - Recursive Input Type Tests

    func testRecursiveInputTypes() throws {
        let schema =
            """
            type Holder {
                id: ID!
            }

            input VehicleEventInputs {
                amendment: AmendmentInput
                other: String
            }

            input AmendmentInput {
                event: VehicleEventInputs
                reason: String
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        let code = generator.code

        // At least one input type should be emitted as class to break the cycle
        XCTAssert(
            code.contains("final class VehicleEventInputs: Codable, Sendable") || code.contains("final class AmendmentInput: Codable, Sendable"),
            "At least one recursive input type should be emitted as final class"
        )

        // The other can remain a struct
        XCTAssert(
            code.contains("struct VehicleEventInputs: Codable, Sendable") || code.contains("struct AmendmentInput: Codable, Sendable"),
            "Non-cycle-breaking input type should remain a struct"
        )
    }

    func testNonRecursiveInputsRemainStructs() throws {
        let schema =
            """
            type Holder {
                id: ID!
            }

            input CreateInput {
                name: String!
            }

            input UpdateInput {
                id: ID!
                name: String
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        let code = generator.code

        // No cycles, so both should be structs
        XCTAssert(code.contains("struct CreateInput: Codable, Sendable"), "CreateInput should be a struct")
        XCTAssert(code.contains("struct UpdateInput: Codable, Sendable"), "UpdateInput should be a struct")
        XCTAssertFalse(code.contains("class"), "No class should be generated for non-recursive inputs")
    }

    // MARK: - Sendable Conformance Tests

    func testSendableConformanceOnAllTypes() throws {
        let schema =
            """
            interface Node {
                id: ID!
            }

            type Dog implements Node {
                id: ID!
                name: String!
                breed: String
            }

            type Cat {
                name: String!
                indoor: Boolean
            }

            union Pet = Dog | Cat

            input FilterInput {
                name: String
            }

            enum Species {
                DOG
                CAT
            }

            type Owner {
                id: ID!
                pet: Pet
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printObjectTypes()

        let expected =
            """

            // MARK: - Types
            extension GeneratedSchema {
              struct Dog: Pet, Node, Codable, Sendable {
                let id: ID
                let name: String
                let breed: String?
              }

              struct Cat: Pet, Codable, Sendable {
                let name: String
                let indoor: Bool?
              }

              struct Owner: Codable, Sendable {
                let id: ID

                func _pet<ContextType>(context: ContextType, args: NoArguments) async throws -> (any Pet)? {
                  guard let resolver = self as? any GeneratedSchema.Owner.Resolver<ContextType> else {
                    throw GeneratedSchemaError(description: "Owner.pet is unimplemented")
                  }

                  return try await resolver.pet(context: context, args: args)
                }

                protocol Resolver<ContextType> {
                  associatedtype ContextType

                  func pet(context: ContextType, args: NoArguments) async throws -> (any Pet)?
                }
              }

              struct FilterInput: Codable, Sendable {
                let name: String?
              }

              enum Species: String, Codable, Sendable {
                case dog = "DOG"
                case cat = "CAT"
              }

              protocol Node: Sendable {
                var id: ID { get }
              }

              protocol Pet: Sendable {
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }

    func testKeywordEscapingComputedFieldSchemaBuilder() throws {
        let schema =
            """
            type Person {
                id: ID!
                name: String!
            }

            type Task {
                id: ID!
                operator(role: String!): Person
            }

            type Query {
                task(id: ID!): Task
            }
            """
        let generator = try Generator(schemas: [schema])
        try generator.printSchemaBuilder()

        let expected =
            """

            // MARK: - Schema Builder
            extension GeneratedSchema {
              static func schema<Resolver>(coders: Coders = Coders()) throws -> Schema<Resolver, Resolver.ContextType> where Resolver: GeneratedResolver {
                try SchemaBuilder(Resolver.self, Resolver.ContextType.self)
                  .setCoders(to: coders)
                  .setFederatedSDL(to: sdl)
                  .add {
                    Type(Person.self, as: "Person") {
                      Field("id", at: \\.id)
                      Field("name", at: \\.name)
                    }
                    Type(Task.self, as: "Task") {
                      Field("id", at: \\.id)
                      Field("operator", at: Task._operator) {
                        Argument("role", at: \\.role)
                      }
                    }
                  }
                  .addQuery {
                    Field("task", at: Resolver.task) {
                      Argument("id", at: \\.id)
                    }
                  }
                  .build()
              }
            }

            """

        XCTAssertNoDifference(expected, generator.code)
    }
}
