import Foundation
import GraphQL

extension Generator {
    public func generate() throws {
        printHeader()
        printImports()
        printNamespace()
        printError()
        printSDL()
        printTypeMapping()
        try printObjectTypes()
        try printObjectResolverDefaultImplementation()
        try printResolverArguments()
        try printResolverProtocol()
        try printResolverProtocolDefaultImplemention()
        try printSchemaBuilder()
    }

    func printHeader() {
        println(
            """
            //
            // DO NOT EDIT.
            // swift-format-ignore-file
            //
            // Generated by GraphQLSchemaCodeGen
            //
            """)
    }

    func printImports() {
        println()
        println(
            """
            import Foundation
            import GraphQL
            import Graphiti
            """)

        for additionalImport in options.additionalImports {
            println("import \(additionalImport)")
        }
    }

    func printNamespace() {
        println()
        println("enum \(data.schemaName) {}")
    }

    func printError() {
        println()
        mark("Error")
        scoped("struct \(data.schemaName)Error: Error", scope: .curly) {
            println("let description: String")
        }
    }

    // TODO: Add support to Graphiti for printing SDL automatically
    func printSDL() {
        let sdl =
            schemas
            .joined(separator: "\n")
            .replacingOccurrences(of: "\"\"\"", with: "\\\"\"\"")

        println()
        mark("SDL")
        scoped("extension \(data.schemaName)", scope: .curly) {
            println("static let sdl: String =")
            println("\"\"\"")
            println(sdl, newLine: false)
            println("\"\"\"")
        }
    }

    func printTypeMapping() {
        guard !options.typeMapping.isEmpty else { return }
        println()
        mark("Type Mapping")
        scoped("extension \(data.schemaName)", scope: .curly) {
            for (key, value) in options.typeMapping.sorted(by: { $0.key < $1.key }) {
                println("typealias \(key) = \(value)")
            }
        }
    }

    func printObjectTypes() throws {
        guard !data.objects.isEmpty || !data.inputs.isEmpty || !data.enums.isEmpty
            || !data.interfaces.isEmpty || !data.unions.isEmpty
        else { return }
        println()
        mark("Types")
        try scoped("extension \(data.schemaName)", scope: .curly) {
            try looped(data.objects) { object in
                // Build conformance list: union protocols + interfaces + Codable
                var conformances: [String] = []
                for (unionName, members) in data.unionMembers {
                    if members.contains(object.name.value) {
                        conformances.append(unionName.escapedIfKeyword)
                    }
                }
                conformances += object.interfaces.map { $0.name.value.escapedIfKeyword }
                conformances.append("Codable")

                try scoped(
                    "struct \(object.name.value.escapedIfKeyword): \(conformances.joined(separator: ", "))",
                    scope: .curly
                ) {
                    let basicFields = object.basicFields(effectiveComputed: data.effectiveComputedFields)
                    let computedFields = object.computedFields(effectiveComputed: data.effectiveComputedFields)

                    for field in basicFields {
                        try println("let \(field.name.value.escapedIfKeyword): \(swiftTypeName(field.type))")
                    }

                    if !computedFields.isEmpty {
                        println()

                        try looped(computedFields) { field in
                            if !field.arguments.isEmpty {
                                try scoped(
                                    "struct \(field.name.value.capitalizeFirst)Arguments: Codable",
                                    scope: .curly
                                ) {
                                    for argument in field.arguments {
                                        try println(
                                            "let \(argument.name.value.escapedIfKeyword): \(swiftTypeName(argument.type))"
                                        )
                                    }
                                }
                                println()
                            }
                            let argumentName = field.arguments.isEmpty ? "No" : field.name.value.capitalizeFirst
                            try scoped(
                                "func _\(field.name.value.escapedIfKeyword)<ContextType>(context: ContextType, args: \(argumentName)Arguments) async throws -> \(swiftTypeName(field.type))",
                                scope: .curly
                            ) {
                                scoped(
                                    "guard let resolver = self as? any \(data.schemaName).\(object.name.value.escapedIfKeyword).Resolver<ContextType> else",
                                    scope: .curly
                                ) {
                                    printThrowError(
                                        "\(object.name.value).\(field.name.value) is unimplemented")
                                }
                                println()
                                println(
                                    "return try await resolver.\(field.name.value.escapedIfKeyword)(context: context, args: args)"
                                )
                            }
                        }

                        println()

                        try scoped("protocol Resolver<ContextType>", scope: .curly) {
                            println("associatedtype ContextType")
                            println()
                            for field in computedFields {
                                let argumentName = field.arguments.isEmpty ? "No" : field.name.value.capitalizeFirst
                                try println(
                                    "func \(field.name.value.escapedIfKeyword)(context: ContextType, args: \(argumentName)Arguments) async throws -> \(swiftTypeName(field.type))"
                                )
                            }
                        }
                    }

                    if try !object.federationKeys().isEmpty { println() }
                    try looped(object.federationKeys()) { key in
                        try scoped("struct \(key.name): Codable", scope: .curly) {
                            for field in key.fields {
                                let objectField = try object.field(named: field)
                                try println(
                                    "let \(objectField.name.value.escapedIfKeyword): \(swiftTypeName(objectField.type))"
                                )
                            }
                        }
                    }
                }
            }
            if !data.inputs.isEmpty {
                println()
                try looped(data.inputs) { object in
                    let keyword = data.classInputTypes.contains(object.name.value) ? "class" : "struct"
                    try scoped("\(keyword) \(object.name.value.escapedIfKeyword): Codable", scope: .curly) {
                        for field in object.fields {
                            try println("let \(field.name.value.escapedIfKeyword): \(swiftTypeName(field.type))")
                        }
                    }
                }
            }
            if !data.enums.isEmpty {
                println()
                looped(data.enums) { object in
                    scoped("enum \(object.name.value.escapedIfKeyword): String, Codable", scope: .curly) {
                        for value in object.values {
                            println(
                                "case \(value.name.value.lowercased().escapedIfKeyword) = \"\(value.name.value)\"")
                        }
                    }
                }
            }
            if !data.interfaces.isEmpty {
                println()
                try looped(data.interfaces) { interface in
                    try scoped("protocol \(interface.name.value.escapedIfKeyword)", scope: .curly) {
                        for field in interface.fields {
                            try println(
                                "var \(field.name.value.escapedIfKeyword): \(swiftTypeName(field.type)) { get }")
                        }
                    }
                }
            }
            if !data.unions.isEmpty {
                println()
                looped(data.unions) { union in
                    scoped("protocol \(union.name.value.escapedIfKeyword): Sendable", scope: .curly) {
                    }
                }
            }
        }
    }

    func printObjectResolverDefaultImplementation() throws {
        guard options.generateDefaultImplementation else { return }
        for object in data.objects {
            let computedFields = object.computedFields(effectiveComputed: data.effectiveComputedFields)
            guard !computedFields.isEmpty else { continue }
            println()
            try scoped("extension \(data.schemaName).\(object.name.value.escapedIfKeyword).Resolver", scope: .curly) {
                try looped(computedFields) { field in
                    let argumentName = field.arguments.isEmpty ? "No" : "\(data.schemaName).\(object.name.value.escapedIfKeyword).\(field.name.value.capitalizeFirst)"
                    try scoped(
                        "func \(field.name.value.escapedIfKeyword)(context: ContextType, args: \(argumentName)Arguments) async throws -> \(swiftTypeName(field.type, namespace: data.schemaName))",
                        scope: .curly
                    ) {
                        printThrowError(
                            "\(object.name.value).\(field.name.value) is unimplemented.")
                    }
                }
            }
        }
    }

    func printResolverArguments() throws {
        println()
        mark("Resolver Arguments")
        try scoped("extension \(data.schemaName)", scope: .curly) {
            try looped(data.queryFields + data.mutationFields + data.subscriptionFields) { field in
                try scoped(
                    "struct \(field.name.value.capitalizeFirst)Arguments: Codable", scope: .curly
                ) {
                    for argument in field.arguments {
                        try println("let \(argument.name.value.escapedIfKeyword): \(swiftTypeName(argument.type))")
                    }
                }
            }
        }
    }

    func printResolverProtocol() throws {
        println()
        mark("Resolver Protocol")
        try scoped("extension \(data.schemaName)", scope: .curly) {
            try scoped("protocol \(data.resolverName): Sendable", scope: .curly) {
                println("associatedtype ContextType")
                println()
                for field in (data.queryFields + data.mutationFields) {
                    try println(
                        "func \(field.name.value.escapedIfKeyword)(context: ContextType, args: \(field.name.value.capitalizeFirst)Arguments) async throws -> \(swiftTypeName(field.type))"
                    )
                }
                for field in data.subscriptionFields {
                    try println(
                        "func \(field.name.value.escapedIfKeyword)(context: ContextType, args: \(field.name.value.capitalizeFirst)Arguments) async throws -> EventStream<\(swiftTypeName(field.type))>"
                    )
                }
                for (object, keys) in data.objectsWithFederationKeys {
                    for key in keys {
                        println(
                            "func \(object.name.value.lowercased().escapedIfKeyword)(context: ContextType, key: \(object.name.value.escapedIfKeyword).\(key.name)) async throws -> \(object.name.value.escapedIfKeyword)?"
                        )
                    }
                }
            }
        }
    }

    func printResolverProtocolDefaultImplemention() throws {
        guard options.generateDefaultImplementation else { return }
        println()
        mark("Resolver Default Implemention")
        try scoped("extension \(data.schemaName).\(data.resolverName)", scope: .curly) {
            try looped(data.queryFields) { field in
                try scoped(
                    "func \(field.name.value.escapedIfKeyword)(context: ContextType, args: \(data.schemaName).\(field.name.value.capitalizeFirst)Arguments) async throws -> \(swiftTypeName(field.type, namespace: data.schemaName))",
                    scope: .curly
                ) {
                    printThrowError("Resolver for query.\(field.name.value) is unimplemented.")
                }
            }
            if !data.mutationFields.isEmpty {
                println()
            }
            try looped(data.mutationFields) { field in
                try scoped(
                    "func \(field.name.value.escapedIfKeyword)(context: ContextType, args: \(data.schemaName).\(field.name.value.capitalizeFirst)Arguments) async throws -> \(swiftTypeName(field.type, namespace: data.schemaName))",
                    scope: .curly
                ) {
                    printThrowError("Resolver for mutation.\(field.name.value) is unimplemented.")
                }
            }
            if !data.subscriptionFields.isEmpty {
                println()
            }
            try looped(data.subscriptionFields) { field in
                try scoped(
                    "func \(field.name.value.escapedIfKeyword)(context: ContextType, args: \(data.schemaName).\(field.name.value.capitalizeFirst)Arguments) async throws -> EventStream<\(swiftTypeName(field.type, namespace: data.schemaName))>",
                    scope: .curly
                ) {
                    printThrowError(
                        "Resolver for subscription.\(field.name.value) is unimplemented.")
                }
            }
            if !data.objectsWithFederationKeys.isEmpty {
                println()
            }
            looped(data.objectsWithFederationKeys) { (object, keys) in
                for key in keys {
                    scoped(
                        "func \(object.name.value.lowercased().escapedIfKeyword)(context: ContextType, key: \(data.schemaName).\(object.name.value.escapedIfKeyword).\(key.name)) async throws -> \(data.schemaName).\(object.name.value.escapedIfKeyword)?",
                        scope: .curly
                    ) {
                        printThrowError(
                            "Resolver for federation.\(object.name.value).\(key.name) is unimplemented."
                        )
                    }
                }
            }
        }
    }

    func printSchemaBuilder() throws {
        println()
        mark("Schema Builder")
        try scoped("extension \(data.schemaName)", scope: .curly) {
            try scoped(
                "static func schema<Resolver>(coders: Coders = Coders()) throws -> Schema<Resolver, Resolver.ContextType> where Resolver: \(data.resolverName)",
                scope: .curly
            ) {
                println("try SchemaBuilder(Resolver.self, Resolver.ContextType.self)")
                indent()
                println(".setCoders(to: coders)")
                println(".setFederatedSDL(to: sdl)")
                try printSchemaBuilderTypes()
                printSchemaBuilderQuery()
                printSchemaBuilderMutation()
                try printSchemaBuilderSubscription()
                println(".build()")
                outdent()
            }
        }
    }

    func printSchemaBuilderTypes() throws {
        try scoped(".add", scope: .curly) {
            for scalar in data.scalars {
                println("Scalar(\(scalar.name.value.escapedIfKeyword).self, as: \"\(scalar.name.value)\")")
                if let description = scalar.description?.value {
                    indent()
                    println(".description(\"\(description)\")")
                    outdent()
                }
            }
            for object in data.objects {
                let objectInterfaces = object.interfaces.map { "\($0.name.value.escapedIfKeyword).self" }
                let typeDeclaration: String
                if objectInterfaces.isEmpty {
                    typeDeclaration =
                        "Type(\(object.name.value.escapedIfKeyword).self, as: \"\(object.name.value)\")"
                } else {
                    typeDeclaration =
                        "Type(\(object.name.value.escapedIfKeyword).self, as: \"\(object.name.value)\", interfaces: [\(objectInterfaces.joined(separator: ", "))])"
                }

                let effectiveOverrides = data.effectiveComputedFields[object.name.value, default: []]
                scoped(typeDeclaration, scope: .curly) {
                    for field in object.fields {
                        let isComputed = !field.arguments.isEmpty || effectiveOverrides.contains(field.name.value)
                        if isComputed {
                            if field.arguments.isEmpty {
                                println("Field(\"\(field.name.value)\", at: \(object.name.value.escapedIfKeyword)._\(field.name.value.escapedIfKeyword))")
                            } else {
                                scoped(
                                    "Field(\"\(field.name.value)\", at: \(object.name.value.escapedIfKeyword)._\(field.name.value.escapedIfKeyword))",
                                    scope: .curly
                                ) {
                                    for argument in field.arguments {
                                        println(
                                            "Argument(\"\(argument.name.value)\", at: \\.\(argument.name.value.escapedIfKeyword))"
                                        )
                                    }
                                }
                            }
                        } else {
                            println("Field(\"\(field.name.value)\", at: \\.\(field.name.value.escapedIfKeyword))")
                        }
                    }
                }
                for keys in try object.federationKeys() {
                    scoped(".key(at: Resolver.\(object.name.value.lowercased().escapedIfKeyword))", scope: .curly) {
                        for field in keys.fields {
                            println("Argument(\"\(field)\", at: \\.\(field.escapedIfKeyword))")
                        }
                    }
                }
            }
            for union in data.unions {
                let memberTypes = data.unionMembers[union.name.value, default: []]
                    .map { "\($0.escapedIfKeyword).self" }
                    .joined(separator: ", ")
                println("Union(\(union.name.value.escapedIfKeyword).self, members: \(memberTypes))")
            }
            for input in data.inputs {
                scoped(
                    "Input(\(input.name.value.escapedIfKeyword).self, as: \"\(input.name.value)\")", scope: .curly
                ) {
                    for field in input.fields {
                        println("InputField(\"\(field.name.value)\", at: \\.\(field.name.value.escapedIfKeyword))")
                    }
                }
            }
            for object in data.enums {
                scoped("Enum(\(object.name.value.escapedIfKeyword).self)", scope: .curly) {
                    for value in object.values {
                        println("Value(.\(value.name.value.lowercased().escapedIfKeyword))")
                    }
                }
            }
            for interface in data.interfaces {
                scoped("Interface(\(interface.name.value.escapedIfKeyword).self)", scope: .curly) {
                    for field in interface.fields {
                        println("Field(\"\(field.name.value)\", at: \\.\(field.name.value.escapedIfKeyword))")
                    }
                }
            }
        }
    }

    func printSchemaBuilderQuery() {
        guard !data.queryFields.isEmpty else { return }
        scoped(".addQuery", scope: .curly) {
            for field in data.queryFields {
                scoped(
                    "Field(\"\(field.name.value)\", at: Resolver.\(field.name.value.escapedIfKeyword))",
                    scope: .curly
                ) {
                    for argument in field.arguments {
                        println(
                            "Argument(\"\(argument.name.value)\", at: \\.\(argument.name.value.escapedIfKeyword))")
                    }
                }
            }
        }
    }

    func printSchemaBuilderMutation() {
        guard !data.mutationFields.isEmpty else { return }
        scoped(".addMutation", scope: .curly) {
            for field in data.mutationFields {
                scoped(
                    "Field(\"\(field.name.value)\", at: Resolver.\(field.name.value.escapedIfKeyword))",
                    scope: .curly
                ) {
                    for argument in field.arguments {
                        println(
                            "Argument(\"\(argument.name.value)\", at: \\.\(argument.name.value.escapedIfKeyword))")
                    }
                }
            }
        }
    }

    func printSchemaBuilderSubscription() throws {
        guard !data.subscriptionFields.isEmpty else { return }
        try scoped(".addSubscription", scope: .curly) {
            for field in data.subscriptionFields {
                try scoped(
                    "SubscriptionField(\"\(field.name.value)\", as: \(swiftTypeName(field.type)).self, atSub: Resolver.\(field.name.value.escapedIfKeyword))",
                    scope: .curly
                ) {
                    for argument in field.arguments {
                        println(
                            "Argument(\"\(argument.name.value)\", at: \\.\(argument.name.value.escapedIfKeyword))")
                    }
                }
            }
        }
    }
}
