name: GraphQLTools Workflow

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit Tests (Swift ${{ matrix.swift }})
    strategy:
      matrix:
        swift: ["5.10", "6.0"]
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: ./build
          key: graphqltools-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            graphqltools-spm-
      - name: Build
        run: swift build
      - name: Test
        run: swift test
