name: GraphQLTools Workflow

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: ./build
          key: graphqltools-spm-${{ hashFiles(Package.resolved) }}
          restore-keys: |
            graphqltools-spm-
      - name: Build
        run: swift build
      - name: Test
        run: swift test
